<a href="https://colab.research.google.com/github/ikabrain/UML501-IKANSH-MAHAJAN-102303754-LabAssignments/blob/main/ML_assign2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 2

Download the dataset (in csv format) from the following link:

https://www.kaggle.com/jahias/microsoft-adventure-works-cycles-customer-data

The Marketing department of Adventure Works Cycles wants to increase sales by targeting specific
customers for a mailing campaign. The company's database contains a list of past customers and a list of
potential new customers. By investigating the attributes of previous bike buyers, the company hopes to
discover patterns that they can then apply to potential customers. They hope to use the discovered patterns
to predict which potential customers are most likely to purchase a bike from Adventure Works Cycles.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df_cus = pd.read_csv("AWCustomers.csv", index_col="CustomerID")
df_cus.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
CustomerID,,,,,,,,,,,,,,,,,,,,,
21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,Australia,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,Canada,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,United States,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,United Kingdom,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,Germany,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [ ]:
df_sales = pd.read_csv("AWSales.csv", index_col="CustomerID")
df_sales.head()

            BikeBuyer  AvgMonthSpend
CustomerID
21173               1          50.97
13249               1          53.11
29350               1          54.08
13503               1          56.93
22803               1          55.41

In [ ]:
df_train = df_cus.join(df_sales, how="left")
df_train.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,,,,,,,,,
21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,Australia,...,M,M,1,3,0,1,81916,2017-03-06,1,50.97
13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,Canada,...,M,M,1,2,1,2,81076,2017-03-06,1,53.11
29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,United States,...,F,S,0,3,0,0,86387,2017-03-06,1,54.08
13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,United Kingdom,...,M,M,1,2,1,2,61481,2017-03-06,1,56.93
22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,Germany,...,M,S,1,1,0,0,51804,2017-03-06,1,55.41

In [ ]:
df_test_classif = pd.read_csv("AWTest-Classification.csv", index_col="CustomerID")
df_test_classif.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
CustomerID,,,,,,,,,,,,,,,,,,,,,
11219,NaN,Charles,NaN,Cook,NaN,6871 Bel Air Dr.,NaN,Woodburn,Oregon,United States,...,High School,Skilled Manual,M,M,1,2,2,2,56100,2017-03-06
11241,NaN,Lisa,NaN,Cai,NaN,"102, rue de Berri",NaN,Les Ulis,Essonne,France,...,Partial College,Skilled Manual,F,S,1,0,0,0,61555,2017-03-06
11352,NaN,Raymond,A,Rodriguez,NaN,"24, impasse Ste-Madeleine",NaN,Pantin,Seine Saint Denis,France,...,Partial College,Clerical,M,M,1,3,0,2,83613,2017-03-06
11904,NaN,Kaylee,NaN,Cook,NaN,5742 Curtis Drive,NaN,Geelong,Victoria,Australia,...,Graduate Degree,Professional,F,S,1,2,0,0,130551,2017-03-06
11908,NaN,Rafael,A,Tang,NaN,8839 Leonard Dr,NaN,South Melbourne,Victoria,Australia,...,Graduate Degree,Professional,M,S,1,2,0,0,135915,2017-03-06

In [ ]:
df_test_regress = pd.read_csv("AWTest-Classification.csv", index_col="CustomerID")
df_test_regress.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
CustomerID,,,,,,,,,,,,,,,,,,,,,
11219,NaN,Charles,NaN,Cook,NaN,6871 Bel Air Dr.,NaN,Woodburn,Oregon,United States,...,High School,Skilled Manual,M,M,1,2,2,2,56100,2017-03-06
11241,NaN,Lisa,NaN,Cai,NaN,"102, rue de Berri",NaN,Les Ulis,Essonne,France,...,Partial College,Skilled Manual,F,S,1,0,0,0,61555,2017-03-06
11352,NaN,Raymond,A,Rodriguez,NaN,"24, impasse Ste-Madeleine",NaN,Pantin,Seine Saint Denis,France,...,Partial College,Clerical,M,M,1,3,0,2,83613,2017-03-06
11904,NaN,Kaylee,NaN,Cook,NaN,5742 Curtis Drive,NaN,Geelong,Victoria,Australia,...,Graduate Degree,Professional,F,S,1,2,0,0,130551,2017-03-06
11908,NaN,Rafael,A,Tang,NaN,8839 Leonard Dr,NaN,South Melbourne,Victoria,Australia,...,Graduate Degree,Professional,M,S,1,2,0,0,135915,2017-03-06

---

## Part I: Based on Feature Selection, Cleaning, and Preprocessing to Construct an Input from Data Source

### (a) Examine the values of each attribute and Select a set of attributes only that would affect to predict future bike buyers to create your input for data mining algorithms. Remove all the unnecessary attributes. (Select features just by analysis)

### (b) Create a new Data Frame with the selected attributes only.

### (c) Determine a Data value type (Discrete, or Continuous, then Nominal, Ordinal, Interval, Ratio) of each attribute in your selection to identify preprocessing tasks to create input for your data mining.

---

## Part II: Data Preprocessing and Transformation

Depending on the data type of each attribute, transform each object from your preprocessed data.
Use all the data rows (~= 18000 rows) with the selected features as input to apply all the tasks below, do
not perform each task on the smaller data set that you got from your random sampling result.

### (a) Handling Null values

### (b) Normalization

### (c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different values

### (d) Standardization/Normalization

### (e) Binarization (One Hot Encoding)

---

## Part III: Calculating Proximity /Correlation Analysis of two features

Make sure each attribute is transformed in a same scale for numeric attributes and Binarization for each
nominal attribute, and each discretized numeric attribute to standardization. Make sure to apply a correct
similarity measure for nominal (one hot encoding)/binary attributes and numeric attributes respectively.

### (a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two following objects of your transformed input data.

### (b) Calculate Correlation between two features Commute Distance and Yearly Income

---