<a href="https://colab.research.google.com/github/ikabrain/UML501-IKANSH-MAHAJAN-102303754-LabAssignments/blob/main/ML_assign2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 2
---

Download the dataset (in csv format) from the following link:

https://www.kaggle.com/jahias/microsoft-adventure-works-cycles-customer-data

The Marketing department of Adventure Works Cycles wants to increase sales by targeting specific
customers for a mailing campaign. The company's database contains a list of past customers and a list of
potential new customers. By investigating the attributes of previous bike buyers, the company hopes to
discover patterns that they can then apply to potential customers. They hope to use the discovered patterns
to predict which potential customers are most likely to purchase a bike from Adventure Works Cycles.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# # Uncomment this if uploading all CSV files from local machine:-
# from google.colab import files
# uploaded = files.upload()
# data_folder = "/content"

In [3]:
from google.colab import drive
drive.mount('/content/drive')
data_folder = "/content/drive/MyDrive/microsoft-adventure-works-cycles-customer-data" # Replace with path of dataset in Drive

Mounted at /content/drive

In [4]:
df_cus = pd.read_csv(f"{data_folder}/AWCustomers.csv", index_col="CustomerID")
df_cus.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
CustomerID,,,,,,,,,,,,,,,,,,,,,
21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,Australia,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,Canada,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,United States,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,United Kingdom,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,Germany,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [5]:
df_sales = pd.read_csv(f"{data_folder}/AWSales.csv", index_col="CustomerID")
df_sales.head()

            BikeBuyer  AvgMonthSpend
CustomerID
21173               1          50.97
13249               1          53.11
29350               1          54.08
13503               1          56.93
22803               1          55.41

In [6]:
df = df_cus.join(df_sales, how="left")
df.head()

,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,CountryRegionName,...,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,,,,,,,,,
21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,Australia,...,M,M,1,3,0,1,81916,2017-03-06,1,50.97
13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,Canada,...,M,M,1,2,1,2,81076,2017-03-06,1,53.11
29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,United States,...,F,S,0,3,0,0,86387,2017-03-06,1,54.08
13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,United Kingdom,...,M,M,1,2,1,2,61481,2017-03-06,1,56.93
22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,Germany,...,M,S,1,1,0,0,51804,2017-03-06,1,55.41

## Part I: Based on Feature Selection, Cleaning, and Preprocessing to Construct an Input from Data Source
---

### (a) Examine the values of each attribute and Select a set of attributes only that would affect to predict future bike buyers to create your input for data mining algorithms. Remove all the unnecessary attributes. (Select features just by analysis)

In [7]:
df.shape

(18361, 25)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18361 entries, 21173 to 16676
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 101 non-null    object
 1   FirstName             18361 non-null  object
 2   MiddleName            10572 non-null  object
 3   LastName              18361 non-null  object
 4   Suffix                3 non-null      object
 5   AddressLine1          18361 non-null  object
 6   AddressLine2          311 non-null    object
 7   City                  18361 non-null  object
 8   StateProvinceName     18361 non-null  object
 9   CountryRegionName     18361 non-null  object
 10  PostalCode            18361 non-null  object
 11  PhoneNumber           18361 non-null  object
 12  BirthDate             18361 non-null  object
 13  Education             18361 non-null  object
 14  Occupation            18361 non-null  object
 15  Gender                18361 non-null  object
 16  MaritalStatus         18361 non-null  object
 17  HomeOwnerFlag         18361 non-null  int64
 18  NumberCarsOwned       18361 non-null  int64
 19  NumberChildrenAtHome  18361 non-null  int64
 20  TotalChildren         18361 non-null  int64
 21  YearlyIncome          18361 non-null  int64
 22  LastUpdated           18361 non-null  object
 23  BikeBuyer             18361 non-null  int64
 24  AvgMonthSpend         18361 non-null  float64
dtypes: float64(1), int64(6), object(18)
memory usage: 3.6+ MB

**Features REMOVED (14 attributes):**

 - Personal identifiers: Names and titles are unique to individuals and don't reveal behavioral patterns
 - Detailed address info: Specific addresses, phone numbers, city & state names are too granular and introduce too many unique values
 - Geographic details: Individual pincodes create too many categories without clear patterns
 - System metadata: LastUpdated is administrative, not behavioral

 **Features KEPT (12 attributes):**

 - Demographics: Age (from BirthDate), Education, Occupation, Gender, MaritalStatus affect lifestyle and purchasing power
 - Financial indicators: YearlyIncome and AvgMonthSpend directly relate to ability and willingness to purchase
 - Lifestyle factors: HomeOwnerFlag, NumberCarsOwned, and children variables indicate life stage and transportation needs
 - Broad geography: Country can indicate buyer behaviour

### (b) Create a new Data Frame with the selected attributes only.

In [9]:
removed_features = [
    "Title",
    "FirstName",
    "MiddleName",
    "LastName",
    "Suffix",
    "AddressLine1",
    "AddressLine2",
    "City",
    "StateProvinceName",
    "PostalCode",
    "PhoneNumber",
    "LastUpdated",
]

In [10]:
from datetime import date

def calculate_float_age(born):
    today = pd.to_datetime(date.today())
    days_lived = (today - born).days
    return days_lived / 365.25   # 365.25 accounts for leap years

In [11]:
df_new = df.drop(removed_features, axis=1)

df_new["BirthDate"] = pd.to_datetime(df_new["BirthDate"])
df_new["BirthDate"] = df_new["BirthDate"].apply(calculate_float_age)
df_new.rename(columns={"BirthDate": "Age"}, inplace=True)

df_new.rename(columns={"CountryRegionName": "Country"}, inplace=True)

df_new["YearlyIncome"] = df_new["YearlyIncome"].astype(float)

df_new.head()

,Country,Age,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,37.817933,Bachelors,Clerical,M,M,1,3,0,1,81916.0,1,50.97
13249,Canada,53.130732,Partial College,Clerical,M,M,1,2,1,2,81076.0,1,53.11
29350,United States,39.827515,Bachelors,Clerical,F,S,0,3,0,0,86387.0,1,54.08
13503,United Kingdom,47.887748,Partial College,Skilled Manual,M,M,1,2,1,2,61481.0,1,56.93
22803,Germany,50.587269,Partial College,Skilled Manual,M,S,1,1,0,0,51804.0,1,55.41

### (c) Determine a Data value type (Discrete, or Continuous, then Nominal, Ordinal, Interval, Ratio) of each attribute in your selection to identify preprocessing tasks to create input for your data mining.

In [12]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18361 entries, 21173 to 16676
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               18361 non-null  object
 1   Age                   18361 non-null  float64
 2   Education             18361 non-null  object
 3   Occupation            18361 non-null  object
 4   Gender                18361 non-null  object
 5   MaritalStatus         18361 non-null  object
 6   HomeOwnerFlag         18361 non-null  int64
 7   NumberCarsOwned       18361 non-null  int64
 8   NumberChildrenAtHome  18361 non-null  int64
 9   TotalChildren         18361 non-null  int64
 10  YearlyIncome          18361 non-null  float64
 11  BikeBuyer             18361 non-null  int64
 12  AvgMonthSpend         18361 non-null  float64
dtypes: float64(3), int64(5), object(5)
memory usage: 2.0+ MB

In [13]:
df_new.nunique()

Country                     6
Age                      8230
Education                   5
Occupation                  5
Gender                      2
MaritalStatus               2
HomeOwnerFlag               2
NumberCarsOwned             6
NumberChildrenAtHome        4
TotalChildren               4
YearlyIncome            15356
BikeBuyer                   2
AvgMonthSpend            1803
dtype: int64

In [14]:
numeric_cols = [
    "Age",
    "NumberCarsOwned",
    "NumberChildrenAtHome",
    "TotalChildren",
    "YearlyIncome",
    "AvgMonthSpend"
]
categorical_cols = [col for col in df_new.columns if col not in numeric_cols]

print(f"Numeric columns:-")
print(numeric_cols)
print(f"Categorical columns:-")
print(categorical_cols)

Numeric columns:-
['Age', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome', 'AvgMonthSpend']
Categorical columns:-
['Country', 'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag', 'BikeBuyer']

In [15]:
discrete_interval_cols = df_new[numeric_cols].select_dtypes(include=["int64"]).columns.tolist()
continuous_ratio_cols = df_new[numeric_cols].select_dtypes(include=["float64"]).columns.tolist()

print(f"Discrete interval columns:-")
print(discrete_interval_cols)
print(f"Continuous ratio columns:-")
print(continuous_ratio_cols)

Discrete interval columns:-
['NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren']
Continuous ratio columns:-
['Age', 'YearlyIncome', 'AvgMonthSpend']

In [16]:
nominal_cols = [
    "Country",
    "Occupation",
    "Gender",
    "MaritalStatus",
    "HomeOwnerFlag",
    "BikeBuyer"
]
ordinal_cols = [col for col in categorical_cols if col not in nominal_cols]

print(f"Nominal columns:-")
print(nominal_cols)
print(f"Ordinal columns:-")
print(ordinal_cols)

Nominal columns:-
['Country', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag', 'BikeBuyer']
Ordinal columns:-
['Education']

In [17]:
target_cols = df_sales.columns.tolist()
target_cols

['BikeBuyer', 'AvgMonthSpend']

## Part II: Data Preprocessing and Transformation
---

Depending on the data type of each attribute, transform each object from your preprocessed data.
Use all the data rows (~= 18000 rows) with the selected features as input to apply all the tasks below, do
not perform each task on the smaller data set that you got from your random sampling result.

### (a) Handling Null values

In [18]:
# Checking if there's any null values at all
print(f"Nulls in train set = {df_new.isnull().sum().sum()}")

Nulls in train set = 0

In [19]:
# # Uncomment if Null vals

# from sklearn.impute import SimpleImputer

# numerical_imputer = SimpleImputer(strategy="mean")
# categorical_imputer = SimpleImputer(strategy="most_frequent")

# df_new[continuous_cols] = numerical_imputer.fit_transform(df_new[continuous_cols])
# df_new[discrete_cols] = categorical_imputer.fit_transform(df_new[discrete_cols])

### (b) Normalization

In [20]:
# Using MinMaxNormalisation on everything except target "AvgMonthSpend"

from sklearn.preprocessing import MinMaxScaler

df_normalised = df_new.copy(deep=True)

transformed_cols = [col for col in numeric_cols if col not in target_cols]

sc = MinMaxScaler()
df_normalised[transformed_cols] = sc.fit_transform(df_new[transformed_cols])

df_normalised.head()

,Country,Age,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,0.186437,Bachelors,Clerical,M,M,1,0.6,0.000000,0.333333,0.496842,1,50.97
13249,Canada,0.404038,Partial College,Clerical,M,M,1,0.4,0.333333,0.666667,0.489453,1,53.11
29350,United States,0.214994,Bachelors,Clerical,F,S,0,0.6,0.000000,0.000000,0.536172,1,54.08
13503,United Kingdom,0.329534,Partial College,Skilled Manual,M,M,1,0.4,0.333333,0.666667,0.317083,1,56.93
22803,Germany,0.367895,Partial College,Skilled Manual,M,S,1,0.2,0.000000,0.000000,0.231958,1,55.41

### (c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different values

In [21]:
df_new.nunique()

Country                     6
Age                      8230
Education                   5
Occupation                  5
Gender                      2
MaritalStatus               2
HomeOwnerFlag               2
NumberCarsOwned             6
NumberChildrenAtHome        4
TotalChildren               4
YearlyIncome            15356
BikeBuyer                   2
AvgMonthSpend            1803
dtype: int64

In [22]:
# So, discretising Age and Yearly Income:-

from sklearn.preprocessing import KBinsDiscretizer

df_discretised = df_new.copy(deep=True)

transformed_cols = ["Age", "YearlyIncome"]

discretiser = KBinsDiscretizer(n_bins=10, encode="ordinal", strategy="quantile")
df_discretised[transformed_cols] = discretiser.fit_transform(df_new[transformed_cols])

df_discretised.head()

,Country,Age,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,3.0,Bachelors,Clerical,M,M,1,3,0,1,6.0,1,50.97
13249,Canada,7.0,Partial College,Clerical,M,M,1,2,1,2,6.0,1,53.11
29350,United States,4.0,Bachelors,Clerical,F,S,0,3,0,0,7.0,1,54.08
13503,United Kingdom,6.0,Partial College,Skilled Manual,M,M,1,2,1,2,4.0,1,56.93
22803,Germany,7.0,Partial College,Skilled Manual,M,S,1,1,0,0,2.0,1,55.41

### (d) Standardization/Normalization

In [23]:
from sklearn.preprocessing import StandardScaler

df_normalised = df_new.copy(deep=True)

transformed_cols = [col for col in numeric_cols if col not in target_cols]

sc = StandardScaler()
df_normalised[transformed_cols] = sc.fit_transform(df_new[transformed_cols])

df_normalised.head()

,Country,Age,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,-0.515315,Bachelors,Clerical,M,M,1,1.892524,-0.594371,0.161342,0.298555,1,50.97
13249,Canada,0.845590,Partial College,Clerical,M,M,1,0.798389,1.163279,1.239753,0.271180,1,53.11
29350,United States,-0.336716,Bachelors,Clerical,F,S,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08
13503,United Kingdom,0.379627,Partial College,Skilled Manual,M,M,1,0.798389,1.163279,1.239753,-0.367401,1,56.93
22803,Germany,0.619543,Partial College,Skilled Manual,M,S,1,-0.295746,-0.594371,-0.917069,-0.682765,1,55.41

### (e) Binarization (One Hot Encoding)

In [24]:
# Columns to be binarised = Non-numeric categorical columns

binarising_cols = [
    col for col in categorical_cols
    if col not in target_cols
    and col not in df_normalised.select_dtypes(np.number)
]

df_normalised[binarising_cols].nunique()

Country          6
Education        5
Occupation       5
Gender           2
MaritalStatus    2
dtype: int64

In [25]:
unique_vals = []
for col in binarising_cols:
    unique_vals.append({"Column": col, "Unique Vals": df_normalised[col].unique().tolist()})

pd.DataFrame(unique_vals).set_index("Column")

                                                     Unique Vals
Column
Country        [Australia, Canada, United States, United King...
Education      [Bachelors, Partial College, High School, Part...
Occupation     [Clerical, Skilled Manual, Manual, Management,...
Gender                                                    [M, F]
MaritalStatus                                             [M, S]

In [26]:
# Handling binary features

df_binarized = df_normalised.copy(deep=True)

df_binarized["MaritalStatus"] = df_normalised["MaritalStatus"].map({"M": 1, "S": 0})
df_binarized.rename({"MaritalStatus": "IsMarried"}, axis=1, inplace=True)

df_binarized["Gender"] = df_normalised["Gender"].map({"M": 1, "F": 0})
df_binarized.rename({"Gender": "IsMale"}, axis=1, inplace=True)

df_binarized.head(3)

,Country,Age,Education,Occupation,IsMale,IsMarried,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,-0.515315,Bachelors,Clerical,1,1,1,1.892524,-0.594371,0.161342,0.298555,1,50.97
13249,Canada,0.845590,Partial College,Clerical,1,1,1,0.798389,1.163279,1.239753,0.271180,1,53.11
29350,United States,-0.336716,Bachelors,Clerical,0,0,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08

In [27]:
# Handling Education as ordinal data

df_order = df_binarized.copy(deep=True)

df_order["Education"] = df_order["Education"].map({
    "Partial High School": 0,
    "High School": 1,
    "Partial College": 2,
    "Bachelors": 3,
    "Graduate Degree": 4,
})
df_order.rename({"Education": "EducationLevel"}, axis=1, inplace=True)

df_order.head(3)

,Country,Age,EducationLevel,Occupation,IsMale,IsMarried,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
CustomerID,,,,,,,,,,,,,
21173,Australia,-0.515315,3,Clerical,1,1,1,1.892524,-0.594371,0.161342,0.298555,1,50.97
13249,Canada,0.845590,2,Clerical,1,1,1,0.798389,1.163279,1.239753,0.271180,1,53.11
29350,United States,-0.336716,3,Clerical,0,0,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08

In [28]:
# Applying dummy encoding

encode_cols = ["Country", "Occupation"]

In [29]:
# METHOD 1: Using OneHotEncoder from SciKit-Learn

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse_output=False) # sparse_output=False returns a dense NumPy array!
encoded = encoder.fit_transform(df_order[encode_cols])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(), index=df_order.index)
df_encoded = pd.concat([df_order.drop(columns=encode_cols), encoded_df], axis=1)

df_encoded.head()

,Age,EducationLevel,IsMale,IsMarried,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend,Country_Canada,Country_France,Country_Germany,Country_United Kingdom,Country_United States,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
CustomerID,,,,,,,,,,,,,,,,,,,,
21173,-0.515315,3,1,1,1,1.892524,-0.594371,0.161342,0.298555,1,50.97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13249,0.845590,2,1,1,1,0.798389,1.163279,1.239753,0.271180,1,53.11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29350,-0.336716,3,0,0,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13503,0.379627,2,1,1,1,0.798389,1.163279,1.239753,-0.367401,1,56.93,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
22803,0.619543,2,1,0,1,-0.295746,-0.594371,-0.917069,-0.682765,1,55.41,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
# METHOD 2: Using Panda's get_dummies()

df_encoded = pd.get_dummies(data=df_order, columns=encode_cols, dtype=int, drop_first=True)
df_encoded.head()

,Age,EducationLevel,IsMale,IsMarried,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend,Country_Canada,Country_France,Country_Germany,Country_United Kingdom,Country_United States,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
CustomerID,,,,,,,,,,,,,,,,,,,,
21173,-0.515315,3,1,1,1,1.892524,-0.594371,0.161342,0.298555,1,50.97,0,0,0,0,0,0,0,0,0
13249,0.845590,2,1,1,1,0.798389,1.163279,1.239753,0.271180,1,53.11,1,0,0,0,0,0,0,0,0
29350,-0.336716,3,0,0,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08,0,0,0,0,1,0,0,0,0
13503,0.379627,2,1,1,1,0.798389,1.163279,1.239753,-0.367401,1,56.93,0,0,0,1,0,0,0,0,1
22803,0.619543,2,1,0,1,-0.295746,-0.594371,-0.917069,-0.682765,1,55.41,0,0,1,0,0,0,0,0,1

## Part III: Calculating Proximity /Correlation Analysis of two features
---

Make sure each attribute is transformed in a same scale for numeric attributes and Binarization for each
nominal attribute, and each discretized numeric attribute to standardization. Make sure to apply a correct
similarity measure for nominal (one hot encoding)/binary attributes and numeric attributes respectively.

In [31]:
df_final = df_encoded.copy(deep=True)
df_final.head(10)

,Age,EducationLevel,IsMale,IsMarried,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend,Country_Canada,Country_France,Country_Germany,Country_United Kingdom,Country_United States,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
CustomerID,,,,,,,,,,,,,,,,,,,,
21173,-0.515315,3,1,1,1,1.892524,-0.594371,0.161342,0.298555,1,50.97,0,0,0,0,0,0,0,0,0
13249,0.845590,2,1,1,1,0.798389,1.163279,1.239753,0.271180,1,53.11,1,0,0,0,0,0,0,0,0
29350,-0.336716,3,0,0,0,1.892524,-0.594371,-0.917069,0.444261,1,54.08,0,0,0,0,1,0,0,0,0
13503,0.379627,2,1,1,1,0.798389,1.163279,1.239753,-0.367401,1,56.93,0,0,0,1,0,0,0,0,1
22803,0.619543,2,1,0,1,-0.295746,-0.594371,-0.917069,-0.682765,1,55.41,0,0,1,0,0,0,0,0,1
22092,0.615163,1,0,1,1,0.798389,2.920930,1.239753,-0.352313,1,49.31,0,0,0,0,1,0,0,0,1
11229,0.901797,2,1,0,1,-0.295746,-0.594371,-0.917069,-1.233031,0,56.01,0,0,0,0,1,0,1,0,0
24179,-1.343099,2,0,1,0,-0.295746,-0.594371,-0.917069,-0.355963,1,49.29,0,0,0,0,0,0,0,0,1
12127,0.454570,2,0,1,1,-1.389881,-0.594371,1.239753,0.361061,1,50.05,0,1,0,0,0,0,0,0,0
19903,0.457003,1,1,0,0,-0.295746,-0.594371,-0.917069,-1.495014,0,54.15,0,1,0,0,0,0,1,0,0

### (a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two following objects of your transformed input data.

In [32]:
# Calculating similarity between 2 binary columns

sim_cols = ["IsMale", "BikeBuyer"]

In [33]:
# Simple Matching Coefficient, SMC = 11 + 00 / 11 + 10 + 01 + 00

# Hamming loss = Sum(A != B) / n = 10 + 01 / 11 + 10 + 01 + 00
# => SMC = 1 - Hamming Loss

from sklearn.metrics import hamming_loss
SMC = 1 - hamming_loss(df_final[sim_cols[0]], df_final[sim_cols[1]])

print(f"Simple Matching Coefficient between {sim_cols[0]} and {sim_cols[1]} = {SMC}")

Simple Matching Coefficient between IsMale and BikeBuyer = 0.5583029246773051

In [34]:
# Jaccard Similarity = M11 / M11 + M10 + M01

from sklearn.metrics import jaccard_score
jaccard = jaccard_score(df_final[sim_cols[0]], df_final[sim_cols[1]])

print(f"Jaccard similarity between {sim_cols[0]} and {sim_cols[1]} = {jaccard}")

Jaccard similarity between IsMale and BikeBuyer = 0.41078174949142693

In [35]:
# Cosine Similarity = A.B / ||A||.||B||

from sklearn.metrics.pairwise import cosine_similarity
cosine = cosine_similarity(df_final[sim_cols].T)[0][1]
# cosine_similarity expects row vectors by default, and returns matrix like similarities between rows 0 & 0, 0 & 1, 1 & 0, and 1 & 1 in each cell!

print(f"Cosine similarity between {sim_cols[0]} and {sim_cols[1]} = {cosine}")

Cosine similarity between IsMale and BikeBuyer = 0.582897138999361

### (b) Calculate Correlation between two features Average Month Spend and Yearly Income

In [36]:
corr = df_final["AvgMonthSpend"].corr(df_final["YearlyIncome"])

print(f"Correlation between AvgMonthSpend and YearlyIncome = {corr}")

Correlation between AvgMonthSpend and YearlyIncome = 0.5301257155563446